---
#   - hosts: tag_Name_DAMPOCAuthor tag_Name_DAMPOCAuthor_ISG
    - hosts: tag_Name_DAMPOCAuthor 
      user: ubuntu
      become: true

      tasks:
      - name: Get Files to deploy
        shell:
          ls -1 /tmp/code_deploy/
        register: files
      - debug: var=files.stdout_lines

      - name: Print files
        shell: "echo {{ item }}"
        with_items: "{{ files.results|map(attribute='stdout_lines')|list }}"
        
