---
#   - hosts: tag_Name_DAMPOCAuthor tag_Name_DAMPOCAuthor_ISG
    - hosts: tag_Name_DAMPOCAuthor 
      user: ubuntu
      become: true

      tasks:
      - name: Get Files to deploy
        shell:
          ls -1 /tmp/code_deploy/
        register: files
      - debug: var=files.stdout_lines

      - name: Print files
        shell: 
           cd /tmp/code_deploy && echo {{ package_admin_url }} {{ item }}
        with_items: "{{ files.stdout_lines }}"
        
