---
#   - hosts: tag_Name_DAMPOCAuthor tag_Name_DAMPOCAuthor_ISG
    - hosts: tag_Name_DAMPOCAuthor 
      user: ubuntu
      become: true

      tasks:
      - name: Get Files to deploy
        shell:
          ls -1 /tmp/code_deploy/
        register: files
      - debug: var=files.stdout_lines

      - name: Install Packages
        shell: 
           #cd /tmp/code_deploy && echo {{ package_admin_url }} {{ item }}
           cd /tmp/code_deploy && curl -u "{{ aem_api_user }}:{{ aem_api_password }}" -X POST -F force=true -F install=true -F file={{ item }} {{ package_admin_url }}
        with_items: "{{ files.stdout_lines }}"
        register: result
      - debug: var=result.stdout_lines
