---
    - hosts: tag_Name_DAMPOCAuthor
      user: ubuntu

      tasks:
      - name: ensure file exists
        aws_s3: bucket=adobedam-ansible-poc object=/FSA-Eligible-Products-List.pdf dest=/tmp/file.pdf mode=get aws_access_key="{{aws_key}}" aws_secret_key="{{aws_secret}}"
         
