---
    - hosts: tag_Name_DAMPOCAuthor
      user: ubuntu
      become: true

      tasks:
      - name: List s3 objects
        aws_s3:
          bucket: "adobedam-ansible-poc"
          prefix: "adam_ci_cd/publisher/"
          mode: list
          aws_access_key: "{{aws_key}}"
          aws_secret_key: "{{aws_secret}}"
        register: s3objects

      - name: Download s3objects
        aws_s3:
          bucket: "adobedam-ansible-poc"
          object: "{{ item }}"
          mode: get
          dest: "/tmp/{{ item|basename }}"
          aws_access_key: "{{aws_key}}"
          aws_secret_key: "{{aws_secret}}"
          overwrite: always
        with_items: "{{ s3objects.s3_keys }}"
        when: not item|basename == ""
