---
    - hosts: tag_Name_DAMPOCAuthor
      user: ubuntu

      tasks:
      - name: Start AEM service
        service:
          name: "{{ aem_service }}"
          state: started

      - name: Check startup log
        shell:
          cat {{ aem_home_directory }}/crx-quickstart/logs/startup.log | grep 'Quikstart started'
        register: cmdline
        failed_when: "cmdline.rc != 0"
        until: cmdline.rc == 0
        retries: 12
        delay: 10
